import './globals.css'
import { IBM_Plex_Sans } from 'next/font/google'

const IBM_plex_sans = IBM_Plex_Sans({ weight: ["400", "700"], subsets: ["latin"] })

export const metadata = {
  title: 'Multi Step Form',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={IBM_plex_sans.className}>{children}</body>
    </html>
  )
}
